stages:
- name: Push Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./api/Dockerfile
      buildContext: ./api
      tag: wei840222/storage-management-system-api
      pushRemote: true
      registry: index.docker.io
timeout: 60
branch:
  include:
  - master
notification: {}
