stages:
# - name: Push Redoc Docker Image
#   steps:
#   - publishImageConfig:
#       dockerfilePath: ./redoc/Dockerfile
#       buildContext: ./redoc
#       tag: wei840222/storage-management-system-redoc
#       pushRemote: true
#       registry: index.docker.io
# - name: Push Api Docker Image
#   steps:
#   - publishImageConfig:
#       dockerfilePath: ./api/Dockerfile
#       buildContext: ./api
#       tag: wei840222/storage-management-system-api
#       pushRemote: true
#       registry: index.docker.io
# - name: Push Web Docker Image
#   steps:
#   - publishImageConfig:
#       dockerfilePath: ./web/Dockerfile
#       buildContext: ./web
#       tag: wei840222/storage-management-system-web
#       pushRemote: true
#       registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./k8s/redoc.yml
timeout: 60
branch:
  include:
  - master
notification: {}
