stages:
- name: Push Redoc Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./redoc/Dockerfile
      buildContext: ./redoc
      tag: wei840222/storage-management-system-redoc:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include:
      - master
    event:
      include:
      - push
      - pull_request
- name: Push Api Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./api/Dockerfile
      buildContext: ./api
      tag: wei840222/storage-management-system-api:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include:
      - master
      - api_dev
    event:
      include:
      - push
      - pull_request
- name: Push Web Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./web/Dockerfile
      buildContext: ./web
      tag: wei840222/storage-management-system-web:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include:
      - master
      - web_dev
    event:
      include:
      - push
      - pull_request
- name: Kustomize
  steps:
  - runScriptConfig:
      image: bitlayer/kustomize:v2.0.3
      shellScript: cd k8s && kustomize edit set image wei840222/storage-management-system-redoc:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        && kustomize edit set image wei840222/storage-management-system-api:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        && kustomize edit set image wei840222/storage-management-system-web:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        && kustomize edit set namespace p-9wwq7-deploy
        && kustomize build . > k8s.yaml && cat k8s.yaml
  when:
    branch:
      include:
      - master
      - k8s_dev
    event:
      include:
      - push
      - pull_request
- name: Deploy Api
  steps:
  - applyYamlConfig:
      path: ./k8s/k8s.yaml
  when:
    branch:
      include:
      - master
      - k8s_dev
      - api_dev
    event:
      include:
      - push
      - pull_request
timeout: 60
branch:
  include:
  - master
  - api_dev
  - web_dev
  - k8s_dev
notification:
  recipients:
  - recipient: http://acl.csie.ntut.edu.tw:5000
    notifier: c-zjq9r:n-47dk8
  condition:
  - Success
  - Changed
  - Failed
