stages:
- name: Push Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./
      tag: wei840222/storage-management-system:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include: master

- name: Kustomize
  steps:
  - runScriptConfig:
      image: bitlayer/kustomize:v2.0.3
      shellScript: cd k8s && kustomize edit set image wei840222/storage-management-system:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
        && kustomize edit set namespace p-cxzl6-deploy
        && kustomize build . > k8s.yaml && cat k8s.yaml
  when:
    branch:
      include: master

- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./k8s/k8s.yaml
  when:
    branch:
      include: master

timeout: 60
branch:
  include: master