version: '2'
services:
    redoc:
        build: ./redoc
        ports:
            - 8081:80
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - db_data:/data/db
    api:
        build: ./api
        ports:
            - 8080:8080
        environment:
            - MONGO_URL=mongodb://mongodb:27017
        depends_on:
            - mongodb
    web:
        build: ./web
        ports:
            - 80:80
        depends_on:
            - api

volumes:
  db_data: