version: '2'
services:
    web:
        build: ./web
        ports:
            - 80:80
        depends_on:
            - api
    api:
        build: ./api
        ports:
            - 8080:8080
        environment:
            - MONGO_URL=mongodb://mongodb:27017
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - db_data:/data/db
    api-doc:
        image: redocly/redoc
        ports:
            - 8081:80
        environment:
            - SPEC_URL=openapi.yaml
        volumes:
            - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml

volumes:
  db_data: