version: '2'
services:
    myapp:
        build: ./src
        ports:
            - 8080:8080
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
          - db_data:/data/db

volumes:
  db_data: