apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api
  namespace: p-4cznw-deploy
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: wei840222/storage-management-system-api
        imagePullPolicy: Always
        env:
        - name: RANCHER_API_URL
          value: https://acl.csie.ntut.edu.tw:3000/v3/project/c-srzf4:p-4cznw
        - name: DEPLOY_NAMESPACE
          value: p-4cznw-deploy
        - name: MONGO_URL
          value: mongodb://wei840222:j04rmp4jo3@mongodb:27017/database
        - name: PROMETHEUS_UI_URL
          value: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/p-4cznw-deploy/services/http:prometheus-grafana:80/proxy/d-solo/319ES9emz
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: p-4cznw-deploy
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: 8080tcp2
    port: 8080
    protocol: TCP
    targetPort: 8080