apiVersion: apps/v1
kind: Deployment
metadata:
  name: redoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redoc
  template:
    metadata:
      labels:
        app: redoc
    spec:
      containers:
      - name: redoc
        image: wei840222/storage-management-system-redoc
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: wei840222/storage-management-system-api
        imagePullPolicy: Always
        env:
        - name: RANCHER_API_URL
          value: https://acl.csie.ntut.edu.tw:3000/v3/project/c-fhjcs:p-wfj6q
        - name: RANCHER_API_TOKEN
          value: token-p2npk:blnj2zzgzfvqjcgf7cft8k44zg49v8pknr7bzhb2dx7rrwzt6wwz6n
        - name: LONGHORN_API_URL
          value: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-fhjcs/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/v1/volumes
        - name: DEPLOY_NAMESPACE
          value: p-wfj6q-deploy
        - name: MONGO_URL
          value: mongodb://wei840222:j04rmp4jo3@mongodb:27017/database
        - name: PROMETHEUS_UI_URL
          value: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-fhjcs/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/jRXvqdgZk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: wei840222/storage-management-system-web
        imagePullPolicy: Always