apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redoc
  namespace: storage-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redoc
  template:
    metadata:
      labels:
        app: redoc
    spec:
      containers:
      - name: redoc
        image: wei840222/storage-management-system-redoc
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redoc
  namespace: storage-management-system
spec:
  type: ClusterIP
  selector:
    app: redoc
  ports:
  - name: 80tcp2
    port: 80
    protocol: TCP
    targetPort: 80