apiVersion: v1
kind: Service
metadata:
  name: redoc
spec:
  type: ClusterIP
  selector:
    app: redoc
  ports:
  - name: 80tcp2
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: 8080tcp2
    port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - name: 80tcp2
    port: 80
    protocol: TCP
    targetPort: 80