apiVersion: v1
kind: Service
metadata:
  name: storage-management-system
spec:
  type: NodePort
  selector:
    app: storage-management-system
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080