apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: web
  namespace: p-4cznw-deploy
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: wei840222/storage-management-system-web
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: p-4cznw-deploy
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - name: 80tcp2
    port: 80
    protocol: TCP
    targetPort: 80